-- Snowflake setup for Cortex AI Services Cost Analyzer
-- This script creates the necessary database objects for the Streamlit app

-- Create database and schema if they don't exist
CREATE DATABASE IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.CORTEX_APPS;

-- Create stage for Streamlit app artifacts
CREATE STAGE IF NOT EXISTS ANALYTICS.CORTEX_APPS.CORTEX_ANALYZER_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stage for Cortex AI Services Cost Analyzer Streamlit app';

-- Grant necessary permissions (adjust roles as needed)
GRANT USAGE ON DATABASE ANALYTICS TO ROLE SYSADMIN;
GRANT USAGE ON SCHEMA ANALYTICS.CORTEX_APPS TO ROLE SYSADMIN;
GRANT READ, WRITE ON STAGE ANALYTICS.CORTEX_APPS.CORTEX_ANALYZER_STAGE TO ROLE SYSADMIN;

-- Grant access to required system views for cost analysis
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE SYSADMIN;

-- Verify access to required tables
SELECT 'ACCOUNT_USAGE.METERING_HISTORY' AS table_name, COUNT(*) AS record_count
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP())
AND SERVICE_TYPE LIKE '%CORTEX%'
UNION ALL
SELECT 'CORTEX_FUNCTIONS_USAGE_HISTORY' AS table_name, COUNT(*) AS record_count  
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_FUNCTIONS_USAGE_HISTORY
WHERE START_TIME >= DATEADD(day, -30, CURRENT_TIMESTAMP());
