-- Cortex AI Services Cost Analyzer - Database Setup
-- This script sets up the necessary database objects for the Streamlit application

-- Create database and schema if they don't exist
CREATE DATABASE IF NOT EXISTS ANALYTICS;
CREATE SCHEMA IF NOT EXISTS ANALYTICS.CORTEX_APPS;

-- Create stage for Streamlit application artifacts
CREATE STAGE IF NOT EXISTS ANALYTICS.CORTEX_APPS.CORTEX_ANALYZER_STAGE;

-- Create dedicated role for Cortex Cost Analyzer
-- Note: These commands require ACCOUNTADMIN or SECURITYADMIN role
CREATE ROLE IF NOT EXISTS CORTEX_COST_ANALYZER_ROLE;

-- Grant usage on application database and schema to the dedicated role
GRANT USAGE ON DATABASE ANALYTICS TO ROLE CORTEX_COST_ANALYZER_ROLE;
GRANT USAGE ON SCHEMA ANALYTICS.CORTEX_APPS TO ROLE CORTEX_COST_ANALYZER_ROLE;
GRANT ALL ON SCHEMA ANALYTICS.CORTEX_APPS TO ROLE CORTEX_COST_ANALYZER_ROLE;

-- Grant warehouse usage for query execution
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE CORTEX_COST_ANALYZER_ROLE;

-- Grant necessary permissions for ACCOUNT_USAGE access
GRANT USAGE ON DATABASE SNOWFLAKE TO ROLE CORTEX_COST_ANALYZER_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE.ACCOUNT_USAGE TO ROLE CORTEX_COST_ANALYZER_ROLE;

-- Grant SELECT on specific ACCOUNT_USAGE views needed for analysis
GRANT SELECT ON SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY TO ROLE CORTEX_COST_ANALYZER_ROLE;
GRANT SELECT ON SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY TO ROLE CORTEX_COST_ANALYZER_ROLE;
GRANT SELECT ON SNOWFLAKE.ACCOUNT_USAGE.CORTEX_FUNCTIONS_USAGE_HISTORY TO ROLE CORTEX_COST_ANALYZER_ROLE;
GRANT SELECT ON SNOWFLAKE.ACCOUNT_USAGE.CORTEX_ANALYST_USAGE_HISTORY TO ROLE CORTEX_COST_ANALYZER_ROLE;
GRANT SELECT ON SNOWFLAKE.ACCOUNT_USAGE.CORTEX_DOCUMENT_PROCESSING_USAGE_HISTORY TO ROLE CORTEX_COST_ANALYZER_ROLE;
GRANT SELECT ON SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_SERVING_USAGE_HISTORY TO ROLE CORTEX_COST_ANALYZER_ROLE;
GRANT SELECT ON SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_DAILY_USAGE_HISTORY TO ROLE CORTEX_COST_ANALYZER_ROLE;

-- Optional: Grant access to ORGANIZATION_USAGE for enhanced reconciliation
-- GRANT USAGE ON SCHEMA SNOWFLAKE.ORGANIZATION_USAGE TO ROLE CORTEX_COST_ANALYZER_ROLE;
-- GRANT SELECT ON SNOWFLAKE.ORGANIZATION_USAGE.METERING_DAILY_HISTORY TO ROLE CORTEX_COST_ANALYZER_ROLE;

-- Grant the role to users who need access to the application
-- Replace <username> with actual usernames or groups
-- GRANT ROLE CORTEX_COST_ANALYZER_ROLE TO USER <username>;
-- GRANT ROLE CORTEX_COST_ANALYZER_ROLE TO ROLE <parent_role>;

-- Set the role as default for Streamlit application
-- This ensures the app runs with proper permissions
-- ALTER USER <app_user> SET DEFAULT_ROLE = 'CORTEX_COST_ANALYZER_ROLE';

-- Create or replace the Streamlit application
-- This will be executed by the Snowflake CLI during deployment
-- CREATE OR REPLACE STREAMLIT ANALYTICS.CORTEX_APPS.CORTEX_AI_COST_ANALYZER
-- ROOT_LOCATION = '@ANALYTICS.CORTEX_APPS.CORTEX_ANALYZER_STAGE'
-- MAIN_FILE = 'app.py'
-- QUERY_WAREHOUSE = 'COMPUTE_WH';